### ISSUE TITLE
Failed while creating a network

### ISSUE THREAD

**Issue by petershaw** [onichandame/nats-action#1]
by adding 
```
    - name: nats-action
      uses: onichandame/nats-action@0.0.0
      with:
        image_version: 2.3.4
        port: 4222    
```

to actions I get an Error 
```
Run onichandame/nats-action@0.0.0
2 with:
3 image_version: 2.3.4
4 port: 4222
5 ports 4222 will be used
6 /usr/bin/sudo docker network create OCB0obAzxa
7 sudo: docker: command not found
8 Error: "The process '/usr/bin/sudo' failed with exit code 1"
```
